# Generated by Django 4.0 on 2022-01-16 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diseños',
            name='entregado',
        ),
        migrations.RemoveField(
            model_name='diseños',
            name='nombre',
        ),
        migrations.AddField(
            model_name='diseños',
            name='autor',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='diseños',
            name='modelo',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
